ACTIVE_CATEGORY_NAVIGATION_TAB = '.tabs-list > li.active .category'
BREADCRUMBS = '.breadcrumbs'
CATEGORY = '.category'
CATEGORY_HEADER = '.category-header > h1'
CATEGORY_NAVIGATION_TABS = '.tabs-list > li'
CONFIRM_EDIT_IN_PROGRESS = '#confirm-edit-in-progress'
DEFAULT_VALUE_SPAN = '.default-value span'
DIALOG_CANCEL = '.dialog .cancel'
DIALOG_CONFIRM = '.dialog .confirm'
HIGHLIGHT = '.highlight'
MATCH_COUNT_ICON = '.match-count'
NEW_VALUE = '.new-value'
OVERRIDE_ACTIVE = '.override > .active'
OVERRIDE_INACTIVE = '.override > :not(.active)'
OVERRIDE_COLLAPSED = '.override.collapsed'
PROPERTIES_TABLE = '.properties-table'
KEY = '.key'
PROPERTY_KEY = '.property-key'
PROPERTY_ELEMENT = '{element}[data-property-key={property_key}]'
PROPERTY_VALUE = '.property-value'
PROPERTY_VALUE_BY_KEY = '.property-value[data-property-key={property_key}]'
PROPERTY_VALUE_CANCEL_BUTTON = '.property-value[data-property-key={property_key}] .cancel-edit-property'
PROPERTY_VALUE_COLLAPSED = '.property-value.collapsed'
PROPERTY_VALUE_EDITING = '.property-value.editing'
PROPERTY_VALUE_ROW = '.property-value[data-property-key={property_key}] .edit-property'
PROPERTY_VALUE_SAVE_BUTTON = '.property-value[data-property-key={property_key}] .save-property'
PROPERTY_VALUE_TEXTAREA = '.property-value[data-property-key={property_key}] textarea'
PROPERTY_VALUE_VALIDATION_ERROR = '.property-value[data-property-key={property_key}] .validation-errors li'
SEARCH_INPUT = '.search-input input'
SEARCH_INPUT_CLEAR_BUTTON = '.search-input .clear-btn'
