import argparse
import csv
import random
import re
import string

from schrodinger.structure import SDReader

DEBUG = False
HEADER = ['Corporate ID', 'Result']
ROW = '{corp_id},{result}'


def log(msg):
    if DEBUG:
        print(msg)


def get_parser():
    """ Get the default parser """

    desc = 'Simple script that sends result as corp id'

    # create the top-level parser
    parser = argparse.ArgumentParser(description=desc)
    parser.add_argument('-i',
                        '--input',
                        dest='input',
                        help='Name of sd file. Note, this is automatically generated by the '
                        'model.')

    return parser


def get_parser_args(parser=None):
    """ Get the args from a parser or use default """

    if not parser:
        parser = get_parser()

    try:
        args = parser.parse_args()
    except IOError as msg:
        parser.error(str(msg))

    return args


def print_csv(args):
    """ Print the csv """
    filename = args.input

    print(','.join(HEADER))
    for structure in SDReader(filename):
        corp_id = structure.property["s_sd_Corporate_ID"].strip()
        print(ROW.format(corp_id=corp_id, result=corp_id))


if __name__ == '__main__':
    args = get_parser_args()
    print_csv(args)
