
# Trigger a manual squish run

name: test_run

on:
  workflow_dispatch:
    inputs:
      SCHRODINGER:
        description: 'path to SCHRODINGER'
        type: string
        # Input has to be provided for the workflow to run
        required: true
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow git pulls and runs squish suites
  test_1:
    # The type of runner that the job will run on
    runs-on: [self-hosted, Linux]
    timeout-minutes: 900
    # Tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v4
    - name: SCHRODINGER
      run: echo ${{ github.event.inputs.SCHRODINGER }}
    - name: Create venv
      run: |
        ${{ github.event.inputs.SCHRODINGER }}/run schrodinger_virtualenv.py test_env.ve
        source test_env.ve/bin/activate
        pip install selenium
        python ${{ github.action_path}}/sel_import_test.py
        cd
        pwd
        find -iname selenium
        ${{ github.event.inputs.SCHRODINGER }}/run run_squish_suites.py --suitedir /scr/carman/Git_Repos/actions_test/test_suites --outdir /scr/carman
        
   
    #- name: Start venv
     # run: source test_env.ve/bin/activate
    #- name: pip selenium
      #run: pip install selenium
    #- name: check python
     # run: which python
    #- name: run python file
      #run: python ${{ github.action_path}}/test_thing.py
   
